/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as HomeLayoutImport } from './routes/home/_layout'

// Create Virtual Routes

const HomeImport = createFileRoute('/home')()
const HomeLayoutIndexLazyImport = createFileRoute('/home/_layout/')()

// Create/Update Routes

const HomeRoute = HomeImport.update({
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutRoute = HomeLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => HomeRoute,
} as any)

const HomeLayoutIndexLazyRoute = HomeLayoutIndexLazyImport.update({
  path: '/',
  getParentRoute: () => HomeLayoutRoute,
} as any).lazy(() =>
  import('./routes/home/_layout/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/home/_layout': {
      preLoaderRoute: typeof HomeLayoutImport
      parentRoute: typeof HomeRoute
    }
    '/home/_layout/': {
      preLoaderRoute: typeof HomeLayoutIndexLazyImport
      parentRoute: typeof HomeLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  HomeRoute.addChildren([
    HomeLayoutRoute.addChildren([HomeLayoutIndexLazyRoute]),
  ]),
])

/* prettier-ignore-end */
