services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_USER=crisprss
      - DB_PASSWORD=crisprss
      - DB_HOST=db
      - CACHE_URL=redis://default:crisprss@cache:6379/0
      - GOOD_JOB_EXECUTION_MODE=external
    volumes:
      - ./:/rails
      - bundler-cache:/usr/local/bundle
    networks:
      - crisprss
    ports:
      - '3000:3000'

  queue:
    build:
      dockerfile: Dockerfile.dev
      context: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_USER=crisprss
      - DB_PASSWORD=crisprss
      - DB_HOST=db
      - CACHE_URL=redis://default:crisprss@cache:6379/0
      - GOOD_JOB_EXECUTION_MODE=external
    volumes:
      - ./:/rails
      - bundler-cache:/usr/local/bundle
    networks:
      - crisprss
    command: bundle exec good_job start

  db:
    image: 'postgres:16-alpine'
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=crisprss
      - POSTGRES_USER=crisprss
      - POSTGRES_DB=crisprss
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - crisprss

  cache:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    restart: unless-stopped
    environment:
      - DFLY_requirepass=crisprss
    networks:
      - crisprss
    volumes:
      - cache-data:/data
    ulimits:
      memlock: -1

volumes:
  bundler-cache:
  postgres-data:
  cache-data:

networks:
  crisprss:
