services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - RAILS_ENV=development
      - DB_USER=crisprss
      - DB_PASSWORD=crisprss
      - DB_HOST=db
    ports:
      - '3000:3000'
    volumes:
      - ./:/rails
      - bundler-cache:/usr/local/bundle
    networks:
      - crisprss

  db:
    image: 'postgres:16-alpine'
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=crisprss
      - POSTGRES_USER=crisprss
      - POSTGRES_DB=crisprss
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - crisprss

volumes:
  bundler-cache:
  postgres-data:

networks:
  crisprss:
